"""add country fields to users

Revision ID: 6436af8b40be
Revises: c3a9a8e5f2be
Create Date: 2026-04-02 11:32:40.293692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6436af8b40be'
down_revision: Union[str, Sequence[str], None] = 'c3a9a8e5f2be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Legacy artifacts that only ever existed on the original prod DB (the
    # initial migration never creates them) — guard so a FRESH database can
    # replay the chain. Prod is already past this revision; nothing re-runs.
    op.execute('DROP TABLE IF EXISTS custom_roles')
    op.execute('ALTER TABLE agents DROP COLUMN IF EXISTS custom_permissions')
    op.execute('ALTER TABLE agents DROP COLUMN IF EXISTS custom_role_id')
    op.add_column('users', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('country_iso', sa.String(length=5), nullable=True))
    op.add_column('users', sa.Column('flag_url', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'flag_url')
    op.drop_column('users', 'country_iso')
    op.drop_column('users', 'country')
    op.add_column('agents', sa.Column('custom_role_id', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('agents', sa.Column('custom_permissions', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_table('custom_roles',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('color', sa.TEXT(), server_default=sa.text("'#589b31'::text"), autoincrement=False, nullable=False),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('protected', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='custom_roles_pkey')
    )
    # ### end Alembic commands ###
