"""add media fields to messages

Revision ID: a3e90c34e4ac
Revises: 6436af8b40be
Create Date: 2026-04-03 02:25:43.057297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a3e90c34e4ac'
down_revision: Union[str, Sequence[str], None] = '6436af8b40be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Same legacy-artifact guard as 6436af8b40be — idempotent for fresh replays.
    op.execute('DROP TABLE IF EXISTS custom_roles')
    op.execute('ALTER TABLE agents DROP COLUMN IF EXISTS custom_permissions')
    op.execute('ALTER TABLE agents DROP COLUMN IF EXISTS custom_role_id')
    op.add_column('messages', sa.Column('name', sa.String(length=100), nullable=True))
    op.add_column('messages', sa.Column('media_id', sa.String(length=200), nullable=True))
    op.add_column('messages', sa.Column('media_caption', sa.Text(), nullable=True))
    op.add_column('messages', sa.Column('mime_type', sa.String(length=100), nullable=True))
    op.add_column('messages', sa.Column('filename', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'filename')
    op.drop_column('messages', 'mime_type')
    op.drop_column('messages', 'media_caption')
    op.drop_column('messages', 'media_id')
    op.drop_column('messages', 'name')
    op.add_column('agents', sa.Column('custom_role_id', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('agents', sa.Column('custom_permissions', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_table('custom_roles',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('color', sa.TEXT(), server_default=sa.text("'#589b31'::text"), autoincrement=False, nullable=False),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('protected', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='custom_roles_pkey')
    )
    # ### end Alembic commands ###
