"""initial_tables

Revision ID: c3a9a8e5f2be
Revises: 
Create Date: 2026-02-21 08:31:06.029148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c3a9a8e5f2be'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'agent', 'readonly', name='agentrole'), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('active_convs', sa.Integer(), nullable=False),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('catalog',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sku', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('aliases', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=True),
    sa.Column('category', sa.String(length=60), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('in_stock', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_table('customer_history',
    sa.Column('wa_id', sa.String(length=30), nullable=False),
    sa.Column('last_status', sa.String(length=30), nullable=True),
    sa.Column('has_open_order', sa.Boolean(), nullable=False),
    sa.Column('last_event', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_chat', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_order', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('counts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('wa_id')
    )
    op.create_table('order_events',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('wa_id', sa.String(length=30), nullable=False),
    sa.Column('session_id', sa.String(length=80), nullable=True),
    sa.Column('event_type', sa.String(length=40), nullable=True),
    sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payment_status', sa.String(length=20), nullable=False),
    sa.Column('fulfillment_status', sa.String(length=20), nullable=False),
    sa.Column('reply_text', sa.Text(), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_events_wa_id'), 'order_events', ['wa_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('wa_id', sa.String(length=30), nullable=False),
    sa.Column('start_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('turns', sa.Integer(), nullable=False),
    sa.Column('ttl_expire_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_wa_id'), 'sessions', ['wa_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('wa_id', sa.String(length=30), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('name_confirmed', sa.Boolean(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('last_text', sa.Text(), nullable=True),
    sa.Column('last_direction', sa.String(length=10), nullable=True),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_wa_id'), 'users', ['wa_id'], unique=True)
    op.create_table('conversations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('wa_id', sa.String(length=30), nullable=False),
    sa.Column('intercept_mode', sa.Enum('ai', 'human', 'paused', name='interceptmode'), nullable=False),
    sa.Column('assigned_agent_id', sa.Uuid(), nullable=True),
    sa.Column('intercept_since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_message_preview', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('open', 'closed', name='convstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_wa_id'), 'conversations', ['wa_id'], unique=True)
    op.create_table('intercepts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.Enum('intercept', 'release', 'transfer', 'approve_draft', name='interceptaction'), nullable=False),
    sa.Column('ai_reply_held', sa.Text(), nullable=True),
    sa.Column('agent_reply_sent', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intercepts_conversation_id'), 'intercepts', ['conversation_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('wa_id', sa.String(length=30), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=True),
    sa.Column('direction', sa.Enum('inbound', 'outbound', name='msgdirection'), nullable=False),
    sa.Column('sender', sa.Enum('user', 'ai', 'human_agent', name='msgsender'), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('media_type', sa.String(length=20), nullable=True),
    sa.Column('media_url', sa.Text(), nullable=True),
    sa.Column('waba_msg_id', sa.String(length=100), nullable=True),
    sa.Column('agent_id', sa.Uuid(), nullable=True),
    sa.Column('ts_ms', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_wa_id'), 'messages', ['wa_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_wa_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_intercepts_conversation_id'), table_name='intercepts')
    op.drop_table('intercepts')
    op.drop_index(op.f('ix_conversations_wa_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_users_wa_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sessions_wa_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_order_events_wa_id'), table_name='order_events')
    op.drop_table('order_events')
    op.drop_table('customer_history')
    op.drop_table('catalog')
    op.drop_table('agents')
    # ### end Alembic commands ###
