import type {
    Conversation,
    MessagesMap,
    Agent,
    RoleDefinitions,
    PermissionDef,
    Order,
    CatalogItem,
    ActivityEntry,
} from "../types";

export const MOCK_CONVERSATIONS: Conversation[] = [
    {
        id: "c1",
        wa_id: "254712001001",
        name: "Wanjiku Kamau",
        channel: "whatsapp",
        intercept_mode: "human",
        status: "open",
        last_message_preview:
            "Can I also get the Devai prefilled cups with the tray?",
        last_message_at: new Date(Date.now() - 2 * 60000).toISOString(),
        assigned_agent_id: "a1",
        unread: 3,
    },
    {
        id: "c2",
        wa_id: "254712002002",
        name: "Otieno Odhiambo",
        channel: "messenger",
        intercept_mode: "ai",
        status: "open",
        last_message_preview: "Do you ship to Kisumu?",
        last_message_at: new Date(Date.now() - 8 * 60000).toISOString(),
        assigned_agent_id: null,
        unread: 0,
    },
    {
        id: "c3",
        wa_id: "254712003003",
        name: "Akinyi Adhiambo",
        channel: "instagram",
        intercept_mode: "human",
        status: "open",
        last_message_preview:
            "What sizes are available for the preaching gown?",
        last_message_at: new Date(Date.now() - 15 * 60000).toISOString(),
        assigned_agent_id: "a2",
        unread: 1,
    },
    {
        id: "c4",
        wa_id: "254712004004",
        name: "Mwangi Njoroge",
        channel: "whatsapp",
        intercept_mode: "paused",
        status: "open",
        last_message_preview:
            "My order arrived but the communion bread was missing",
        last_message_at: new Date(Date.now() - 45 * 60000).toISOString(),
        assigned_agent_id: null,
        unread: 0,
    },
    {
        id: "c5",
        wa_id: "254712005005",
        name: "Chebet Korir",
        channel: "email",
        intercept_mode: "ai",
        status: "open",
        last_message_preview:
            "I'd like to order altar wine for our Easter service",
        last_message_at: new Date(Date.now() - 90 * 60000).toISOString(),
        assigned_agent_id: null,
        unread: 0,
    },
    {
        id: "c6",
        wa_id: "254712006006",
        name: "Mutua Munyao",
        channel: "messenger",
        intercept_mode: "human",
        status: "closed",
        last_message_preview:
            "Thank you, the stainless steel tray is exactly what we needed!",
        last_message_at: new Date(Date.now() - 3 * 3600000).toISOString(),
        assigned_agent_id: "a1",
        unread: 0,
    },
    {
        id: "c7",
        wa_id: "254712007007",
        name: "Njeri Gitau",
        channel: "instagram",
        intercept_mode: "ai",
        status: "open",
        last_message_preview: "Is the clergy shirt available in white, size L?",
        last_message_at: new Date(Date.now() - 12 * 60000).toISOString(),
        assigned_agent_id: null,
        unread: 2,
    },
    {
        id: "c8",
        wa_id: "254712008008",
        name: "Kipchoge Ruto",
        channel: "sms",
        intercept_mode: "ai",
        status: "open",
        last_message_preview:
            "Please confirm my order for the Basic Communion Pack",
        last_message_at: new Date(Date.now() - 25 * 60000).toISOString(),
        assigned_agent_id: null,
        unread: 0,
    },
    {
        id: "c9",
        wa_id: "254712009009",
        name: "Zawadi Muthoni",
        channel: "whatsapp",
        intercept_mode: "human",
        status: "open",
        last_message_preview:
            "We need a children's Bible in Swahili, do you have one?",
        last_message_at: new Date(Date.now() - 5 * 60000).toISOString(),
        assigned_agent_id: "a2",
        unread: 1,
    },
    {
        id: "c10",
        wa_id: "254712010010",
        name: "Baraka Omondi",
        channel: "email",
        intercept_mode: "paused",
        status: "closed",
        last_message_preview:
            "Refund for the duplicate order has been processed",
        last_message_at: new Date(Date.now() - 6 * 3600000).toISOString(),
        assigned_agent_id: "a1",
        unread: 0,
    },
];

export const MOCK_MESSAGES: MessagesMap = {
    c1: [
        {
            id: "m1",
            direction: "inbound",
            sender: "user",
            text: "Hello, I need to buy a communion tray for our church. We have about 80 members.",
            created_at: new Date(Date.now() - 20 * 60000).toISOString(),
        },
        {
            id: "m2",
            direction: "outbound",
            sender: "ai",
            text: "Hello Wanjiku! 🙏 Welcome to Bethany House. For 80 members, we'd recommend the Rectangle Stainless Steel Communion Tray (KES 10,000) or our Silver Tray Large 72 Cups (KES 25,000). Both come with matching lids. Which would you prefer?",
            created_at: new Date(Date.now() - 19 * 60000).toISOString(),
        },
        {
            id: "m3",
            direction: "inbound",
            sender: "user",
            text: "The stainless steel one sounds good. Does it come with cups?",
            created_at: new Date(Date.now() - 18 * 60000).toISOString(),
        },
        {
            id: "m4",
            direction: "outbound",
            sender: "ai",
            text: "The tray comes with cup inserts but not the cups themselves. You can add Silver Communion Cups separately. Shall I put together a bundle for you?",
            created_at: new Date(Date.now() - 17 * 60000).toISOString(),
        },
        {
            id: "m5",
            direction: "inbound",
            sender: "user",
            text: "Yes please. We're based in Nairobi, Karen area.",
            created_at: new Date(Date.now() - 10 * 60000).toISOString(),
        },
        {
            id: "m6",
            direction: "outbound",
            sender: "human_agent",
            text: "Hi Wanjiku, I'm Sarah from Bethany House. Great news — we offer free delivery within Nairobi! I'm putting together your order now. Could you confirm: 1x Rectangle Stainless Steel Tray + Silver Cups?",
            created_at: new Date(Date.now() - 8 * 60000).toISOString(),
        },
        {
            id: "m7",
            direction: "inbound",
            sender: "user",
            text: "Can I also get the Devai prefilled cups with the tray?",
            created_at: new Date(Date.now() - 2 * 60000).toISOString(),
        },
    ],
    c2: [
        {
            id: "m1",
            direction: "inbound",
            sender: "user",
            text: "Do you ship to Kisumu?",
            created_at: new Date(Date.now() - 9 * 60000).toISOString(),
        },
        {
            id: "m2",
            direction: "outbound",
            sender: "ai",
            text: "Yes! We ship across East Africa. For orders above KES 2,000, we ship to Kisumu with next-day delivery. What products are you interested in?",
            created_at: new Date(Date.now() - 8 * 60000).toISOString(),
        },
    ],
    c3: [
        {
            id: "m1",
            direction: "inbound",
            sender: "user",
            text: "Hi! Saw your page on Instagram. I'm looking for a preaching gown for my pastor.",
            created_at: new Date(Date.now() - 18 * 60000).toISOString(),
        },
        {
            id: "m2",
            direction: "outbound",
            sender: "ai",
            text: "Wonderful! Our Preaching Gown is made with 85% polyester, no-wrinkle fabric, and features cross-print embroidery. It's ideal for pulpit use. We have multiple sizes. What is your pastor's approximate height and build?",
            created_at: new Date(Date.now() - 17 * 60000).toISOString(),
        },
        {
            id: "m3",
            direction: "inbound",
            sender: "user",
            text: "What sizes are available for the preaching gown?",
            created_at: new Date(Date.now() - 15 * 60000).toISOString(),
        },
    ],
    c7: [
        {
            id: "m1",
            direction: "inbound",
            sender: "user",
            text: "Good morning! Do you have clergy shirts in stock?",
            created_at: new Date(Date.now() - 14 * 60000).toISOString(),
        },
        {
            id: "m2",
            direction: "outbound",
            sender: "ai",
            text: "Good morning! Yes, we stock the Clergy Shirt U-Collar — short sleeve, color-fast, made for professional clergy wear. Available in black and white. What size do you need?",
            created_at: new Date(Date.now() - 13 * 60000).toISOString(),
        },
        {
            id: "m3",
            direction: "inbound",
            sender: "user",
            text: "Is the clergy shirt available in white, size L?",
            created_at: new Date(Date.now() - 12 * 60000).toISOString(),
        },
    ],
};

export const AI_DRAFT =
    "Yes, we have the Devai Prefilled Cups (KES 800 per pack) — they include both the wine/juice and bread wafer in a single sealed cup, perfect for hygienic communion. Would you like to add a pack to your tray order? Your updated total would be KES 10,800.";

export const MOCK_AGENTS: Agent[] = [
    {
        id: "a1",
        name: "Sarah Kamau",
        email: "sarah@bethanyhouse.co.ke",
        role: "agent",
        permissions: ["view_conversations", "send_messages", "intercept"],
        is_available: true,
        active_convs: 3,
        last_seen_at: new Date(Date.now() - 5 * 60000).toISOString(),
        joined_at: "2024-01-15",
        department: "Support",
    },
    {
        id: "a2",
        name: "James Otieno",
        email: "james@bethanyhouse.co.ke",
        role: "agent",
        permissions: ["view_conversations", "send_messages", "intercept"],
        is_available: true,
        active_convs: 1,
        last_seen_at: new Date(Date.now() - 2 * 60000).toISOString(),
        joined_at: "2024-02-20",
        department: "Support",
    },
    {
        id: "a3",
        name: "Moses Mwicigi",
        email: "mwicigi@bethanyhouse.co.ke",
        role: "admin",
        permissions: ["all"],
        is_available: false,
        active_convs: 0,
        last_seen_at: new Date(Date.now() - 2 * 3600000).toISOString(),
        joined_at: "2023-11-01",
        department: "Management",
    },
    {
        id: "a4",
        name: "David Mwangi",
        email: "david@bethanyhouse.co.ke",
        role: "readonly",
        permissions: ["view_conversations", "view_orders"],
        is_available: true,
        active_convs: 0,
        last_seen_at: new Date(Date.now() - 30 * 60000).toISOString(),
        joined_at: "2024-03-10",
        department: "Analytics",
    },
];

export const ROLE_DEFINITIONS: RoleDefinitions = {
    admin: {
        label: "Admin",
        color: "#f59e0b",
        description: "Full system access",
        permissions: [
            "view_conversations",
            "send_messages",
            "intercept",
            "manage_agents",
            "manage_catalog",
            "view_orders",
            "manage_orders",
            "view_analytics",
            "manage_settings",
        ],
    },
    agent: {
        label: "Agent",
        color: "#3b82f6",
        description: "Handle conversations & orders",
        permissions: [
            "view_conversations",
            "send_messages",
            "intercept",
            "view_orders",
        ],
    },
    readonly: {
        label: "Viewer",
        color: "#10b981",
        description: "Read-only access",
        permissions: ["view_conversations", "view_orders"],
    },
    supervisor: {
        label: "Supervisor",
        color: "#f97316",
        description: "Oversee agents & convs",
        permissions: [
            "view_conversations",
            "send_messages",
            "intercept",
            "manage_agents",
            "view_orders",
            "view_analytics",
        ],
    },
};

export const ALL_PERMISSIONS: PermissionDef[] = [
    {
        key: "view_conversations",
        label: "View Conversations",
        group: "Conversations",
    },
    { key: "send_messages", label: "Send Messages", group: "Conversations" },
    {
        key: "intercept",
        label: "Intercept / Release AI",
        group: "Conversations",
    },
    { key: "manage_agents", label: "Manage Agents", group: "Team" },
    { key: "view_orders", label: "View Orders", group: "Orders" },
    { key: "manage_orders", label: "Manage Orders", group: "Orders" },
    { key: "manage_catalog", label: "Manage Catalog", group: "Catalog" },
    { key: "view_analytics", label: "View Analytics", group: "Analytics" },
    { key: "manage_settings", label: "System Settings", group: "Settings" },
];

export const MOCK_ORDERS: Order[] = [
    {
        id: "o1",
        wa_id: "254712001001",
        customer_name: "Wanjiku Kamau",
        items: [
            {
                name: "Rectangle Stainless Steel Communion Tray",
                qty: 1,
                total: 10000,
            },
            { name: "Devai Prefilled Cups", qty: 1, total: 800 },
        ],
        subtotal: 10800,
        status: "pending",
        payment: "mpesa",
        created_at: new Date(Date.now() - 18 * 60000).toISOString(),
    },
    {
        id: "o2",
        wa_id: "254712003003",
        customer_name: "Akinyi Adhiambo",
        items: [
            { name: "Preaching Gown", qty: 1, total: 3500 },
            { name: "Clergy Shirt U-Collar", qty: 2, total: 3200 },
        ],
        subtotal: 6700,
        status: "confirmed",
        payment: "cod",
        created_at: new Date(Date.now() - 35 * 60000).toISOString(),
    },
    {
        id: "o3",
        wa_id: "254712006006",
        customer_name: "Mutua Munyao",
        items: [
            {
                name: "Rectangle Stainless Steel Communion Tray",
                qty: 1,
                total: 10000,
            },
        ],
        subtotal: 10000,
        status: "delivered",
        payment: "mpesa",
        created_at: new Date(Date.now() - 3 * 3600000).toISOString(),
    },
    {
        id: "o4",
        wa_id: "254712005005",
        customer_name: "Chebet Korir",
        items: [
            { name: "Altar Wine (750ml)", qty: 3, total: 5400 },
            { name: "Holy Communion Bread", qty: 1, total: 600 },
        ],
        subtotal: 6000,
        status: "confirmed",
        payment: "mpesa",
        created_at: new Date(Date.now() - 60 * 60000).toISOString(),
    },
];

export const MOCK_CATALOG: CatalogItem[] = [
    {
        id: "cat1",
        sku: "AW-001",
        name: "Altar Wine (750ml)",
        category: "Communion Items",
        price: 1800,
        in_stock: true,
        description:
            "KCCB-approved medium-sweet sacramental wine from 100% pure red grapes",
    },
    {
        id: "cat2",
        sku: "RSST-002",
        name: "Rectangle Stainless Steel Communion Tray",
        category: "Communion Items",
        price: 10000,
        in_stock: true,
        description:
            "Durable stainless steel tray with lid, holds standard communion cups",
    },
    {
        id: "cat3",
        sku: "DEV-003",
        name: "Devai Prefilled Cups",
        category: "Communion Items",
        price: 800,
        in_stock: true,
        description:
            "Hygienic single-serving prefilled communion cups, 100% recyclable",
    },
    {
        id: "cat4",
        sku: "HCB-004",
        name: "Holy Communion Bread",
        category: "Communion Items",
        price: 600,
        in_stock: true,
        description: "Airtight-sealed wafers with up to 2-year shelf life",
    },
    {
        id: "cat5",
        sku: "PG-005",
        name: "Preaching Gown",
        category: "Clergy Vestments",
        price: 3500,
        in_stock: true,
        description:
            "85% polyester no-wrinkle fabric, cross-print embroidery, multiple sizes",
    },
    {
        id: "cat6",
        sku: "CSU-006",
        name: "Clergy Shirt U-Collar",
        category: "Clergy Vestments",
        price: 1600,
        in_stock: true,
        description:
            "Short sleeve, color-fast, professional clergy wear — black & white",
    },
    {
        id: "cat7",
        sku: "BCP-007",
        name: "Basic Communion Pack",
        category: "Communion Items",
        price: 2100,
        in_stock: true,
        description:
            "Starter pack with tray, cups, and communion bread for small congregations",
    },
    {
        id: "cat8",
        sku: "NIV-008",
        name: "NIV Trimline Bible",
        category: "Books & Gifts",
        price: 1200,
        in_stock: true,
        description:
            "Compact NIV Bible, ideal for personal and congregational use",
    },
    {
        id: "cat9",
        sku: "BYK-009",
        name: "Biblia Yangu Kubwa Niipendayo",
        category: "Books & Gifts",
        price: 1450,
        in_stock: true,
        description:
            "Large-print Swahili Bible, popular for worship and personal reading",
    },
    {
        id: "cat10",
        sku: "SDS-010",
        name: "Stole Double Sided",
        category: "Clergy Vestments",
        price: 3600,
        in_stock: false,
        description:
            "Reversible liturgical stole for clergy, available in seasonal colours",
    },
];

export const ACTIVITY_LOG: ActivityEntry[] = [
    {
        id: 1,
        user: "Sarah Kamau",
        action: "Intercepted conversation",
        target: "Wanjiku Kamau",
        at: new Date(Date.now() - 8 * 60000).toISOString(),
    },
    {
        id: 2,
        user: "Moses Mwicigi",
        action: "Added agent",
        target: "David Mwangi",
        at: new Date(Date.now() - 2 * 3600000).toISOString(),
    },
    {
        id: 3,
        user: "James Otieno",
        action: "Closed conversation",
        target: "Mutua Munyao",
        at: new Date(Date.now() - 3 * 3600000).toISOString(),
    },
    {
        id: 4,
        user: "Sarah Kamau",
        action: "Updated order status",
        target: "#o2 → confirmed",
        at: new Date(Date.now() - 4 * 3600000).toISOString(),
    },
    {
        id: 5,
        user: "Moses Mwicigi",
        action: "Edited catalog item",
        target: "Stole Double Sided (out of stock)",
        at: new Date(Date.now() - 5 * 3600000).toISOString(),
    },
];
