import type {
    Conversation,
    MessagesMap,
    Agent,
    RoleDefinitions,
    PermissionDef,
    Order,
    CatalogItem,
    ActivityEntry,
} from "../types";

export const MOCK_CONVERSATIONS: Conversation[] = [
    {
        id: "c1",
        wa_id: "254712001001",
        name: "Amara Osei",
        channel: "whatsapp",
        intercept_mode: "human",
        status: "open",
        last_message_preview: "I want to add plantain to my order",
        last_message_at: new Date(Date.now() - 2 * 60000).toISOString(),
        assigned_agent_id: "a1",
        unread: 3,
    },
    {
        id: "c2",
        wa_id: "254712002002",
        name: "Kofi Mensah",
        channel: "messenger",
        intercept_mode: "ai",
        status: "open",
        last_message_preview: "What's the delivery time?",
        last_message_at: new Date(Date.now() - 8 * 60000).toISOString(),
        assigned_agent_id: null,
        unread: 0,
    },
    {
        id: "c3",
        wa_id: "254712003003",
        name: "Zara Diallo",
        channel: "instagram",
        intercept_mode: "human",
        status: "open",
        last_message_preview: "Can I pay cash on delivery?",
        last_message_at: new Date(Date.now() - 15 * 60000).toISOString(),
        assigned_agent_id: "a2",
        unread: 1,
    },
    {
        id: "c4",
        wa_id: "254712004004",
        name: "Nana Acheampong",
        channel: "whatsapp",
        intercept_mode: "paused",
        status: "open",
        last_message_preview: "I didn't receive my order",
        last_message_at: new Date(Date.now() - 45 * 60000).toISOString(),
        assigned_agent_id: null,
        unread: 0,
    },
    {
        id: "c5",
        wa_id: "254712005005",
        name: "Esi Boateng",
        channel: "email",
        intercept_mode: "ai",
        status: "open",
        last_message_preview: "Hi, I'd like to order jollof rice",
        last_message_at: new Date(Date.now() - 90 * 60000).toISOString(),
        assigned_agent_id: null,
        unread: 0,
    },
    {
        id: "c6",
        wa_id: "254712006006",
        name: "Kweku Asante",
        channel: "messenger",
        intercept_mode: "human",
        status: "closed",
        last_message_preview: "Thanks, order confirmed!",
        last_message_at: new Date(Date.now() - 3 * 3600000).toISOString(),
        assigned_agent_id: "a1",
        unread: 0,
    },
    {
        id: "c7",
        wa_id: "254712007007",
        name: "Abena Poku",
        channel: "instagram",
        intercept_mode: "ai",
        status: "open",
        last_message_preview: "Is the fufu combo available tonight?",
        last_message_at: new Date(Date.now() - 12 * 60000).toISOString(),
        assigned_agent_id: null,
        unread: 2,
    },
    {
        id: "c8",
        wa_id: "254712008008",
        name: "Yaw Darko",
        channel: "sms",
        intercept_mode: "ai",
        status: "open",
        last_message_preview: "Please confirm my order #o3",
        last_message_at: new Date(Date.now() - 25 * 60000).toISOString(),
        assigned_agent_id: null,
        unread: 0,
    },
    {
        id: "c9",
        wa_id: "254712009009",
        name: "Akua Mensah",
        channel: "whatsapp",
        intercept_mode: "human",
        status: "open",
        last_message_preview: "Can I get a vegetarian option?",
        last_message_at: new Date(Date.now() - 5 * 60000).toISOString(),
        assigned_agent_id: "a2",
        unread: 1,
    },
    {
        id: "c10",
        wa_id: "254712010010",
        name: "Kwame Asiedu",
        channel: "email",
        intercept_mode: "paused",
        status: "closed",
        last_message_preview: "Refund processed successfully",
        last_message_at: new Date(Date.now() - 6 * 3600000).toISOString(),
        assigned_agent_id: "a1",
        unread: 0,
    },
];

export const MOCK_MESSAGES: MessagesMap = {
    c1: [
        {
            id: "m1",
            direction: "inbound",
            sender: "user",
            text: "Hello, I want to order some food",
            created_at: new Date(Date.now() - 20 * 60000).toISOString(),
        },
        {
            id: "m2",
            direction: "outbound",
            sender: "ai",
            text: "Hello Amara! 🌟 Welcome to Neema. What would you like to order today?",
            created_at: new Date(Date.now() - 19 * 60000).toISOString(),
        },
        {
            id: "m3",
            direction: "inbound",
            sender: "user",
            text: "I'll take the Jollof rice combo x2",
            created_at: new Date(Date.now() - 18 * 60000).toISOString(),
        },
        {
            id: "m4",
            direction: "outbound",
            sender: "ai",
            text: "Great choice! 2x Jollof Rice Combo added. Subtotal: KES 800. What's your delivery address?",
            created_at: new Date(Date.now() - 17 * 60000).toISOString(),
        },
        {
            id: "m5",
            direction: "inbound",
            sender: "user",
            text: "Westlands, near the Shell station",
            created_at: new Date(Date.now() - 10 * 60000).toISOString(),
        },
        {
            id: "m6",
            direction: "outbound",
            sender: "human_agent",
            text: "Hi Amara, I'm Sarah your agent. I've noted your address. Can you be more specific? Which road?",
            created_at: new Date(Date.now() - 8 * 60000).toISOString(),
        },
        {
            id: "m7",
            direction: "inbound",
            sender: "user",
            text: "I want to add plantain to my order",
            created_at: new Date(Date.now() - 2 * 60000).toISOString(),
        },
    ],
    c2: [
        {
            id: "m1",
            direction: "inbound",
            sender: "user",
            text: "What's the delivery time?",
            created_at: new Date(Date.now() - 8 * 60000).toISOString(),
        },
        {
            id: "m2",
            direction: "outbound",
            sender: "ai",
            text: "Delivery usually takes 30–45 minutes depending on your location. Would you like to place an order?",
            created_at: new Date(Date.now() - 7 * 60000).toISOString(),
        },
    ],
    c3: [
        {
            id: "m1",
            direction: "inbound",
            sender: "user",
            text: "Hi! Saw your post on Instagram. Can I pay cash on delivery?",
            created_at: new Date(Date.now() - 18 * 60000).toISOString(),
        },
        {
            id: "m2",
            direction: "outbound",
            sender: "ai",
            text: "Yes! We accept cash on delivery for all orders within Nairobi. What would you like to order?",
            created_at: new Date(Date.now() - 17 * 60000).toISOString(),
        },
        {
            id: "m3",
            direction: "inbound",
            sender: "user",
            text: "Can I pay cash on delivery?",
            created_at: new Date(Date.now() - 15 * 60000).toISOString(),
        },
    ],
    c7: [
        {
            id: "m1",
            direction: "inbound",
            sender: "user",
            text: "Is the fufu combo available tonight?",
            created_at: new Date(Date.now() - 14 * 60000).toISOString(),
        },
        {
            id: "m2",
            direction: "outbound",
            sender: "ai",
            text: "Yes! Fufu Combo is available. Would you like to order? It's KES 480.",
            created_at: new Date(Date.now() - 13 * 60000).toISOString(),
        },
        {
            id: "m3",
            direction: "inbound",
            sender: "user",
            text: "Yes please, 1 fufu combo. Delivery to Kilimani.",
            created_at: new Date(Date.now() - 12 * 60000).toISOString(),
        },
    ],
};

export const AI_DRAFT =
    "I'd be happy to add fried plantain to your order! That will be an additional KES 150. Your updated total is KES 950. Shall I confirm?";

export const MOCK_AGENTS: Agent[] = [
    {
        id: "a1",
        name: "Sarah Kamau",
        email: "sarah@neema.co",
        role: "agent",
        permissions: ["view_conversations", "send_messages", "intercept"],
        is_available: true,
        active_convs: 3,
        last_seen_at: new Date(Date.now() - 5 * 60000).toISOString(),
        joined_at: "2024-01-15",
        department: "Support",
    },
    {
        id: "a2",
        name: "James Otieno",
        email: "james@neema.co",
        role: "agent",
        permissions: ["view_conversations", "send_messages", "intercept"],
        is_available: true,
        active_convs: 1,
        last_seen_at: new Date(Date.now() - 2 * 60000).toISOString(),
        joined_at: "2024-02-20",
        department: "Support",
    },
    {
        id: "a3",
        name: "Priya Sharma",
        email: "priya@neema.co",
        role: "admin",
        permissions: ["all"],
        is_available: false,
        active_convs: 0,
        last_seen_at: new Date(Date.now() - 2 * 3600000).toISOString(),
        joined_at: "2023-11-01",
        department: "Management",
    },
    {
        id: "a4",
        name: "David Mwangi",
        email: "david@neema.co",
        role: "readonly",
        permissions: ["view_conversations", "view_orders"],
        is_available: true,
        active_convs: 0,
        last_seen_at: new Date(Date.now() - 30 * 60000).toISOString(),
        joined_at: "2024-03-10",
        department: "Analytics",
    },
];

export const ROLE_DEFINITIONS: RoleDefinitions = {
    admin: {
        label: "Admin",
        color: "#f59e0b",
        description: "Full system access",
        permissions: [
            "view_conversations",
            "send_messages",
            "intercept",
            "manage_agents",
            "manage_catalog",
            "view_orders",
            "manage_orders",
            "view_analytics",
            "manage_settings",
        ],
    },
    agent: {
        label: "Agent",
        color: "#3b82f6",
        description: "Handle conversations & orders",
        permissions: [
            "view_conversations",
            "send_messages",
            "intercept",
            "view_orders",
        ],
    },
    readonly: {
        label: "Viewer",
        color: "#10b981",
        description: "Read-only access",
        permissions: ["view_conversations", "view_orders"],
    },
    supervisor: {
        label: "Supervisor",
        color: "#f97316",
        description: "Oversee agents & convs",
        permissions: [
            "view_conversations",
            "send_messages",
            "intercept",
            "manage_agents",
            "view_orders",
            "view_analytics",
        ],
    },
};

export const ALL_PERMISSIONS: PermissionDef[] = [
    {
        key: "view_conversations",
        label: "View Conversations",
        group: "Conversations",
    },
    { key: "send_messages", label: "Send Messages", group: "Conversations" },
    {
        key: "intercept",
        label: "Intercept / Release AI",
        group: "Conversations",
    },
    { key: "manage_agents", label: "Manage Agents", group: "Team" },
    { key: "view_orders", label: "View Orders", group: "Orders" },
    { key: "manage_orders", label: "Manage Orders", group: "Orders" },
    { key: "manage_catalog", label: "Manage Catalog", group: "Catalog" },
    { key: "view_analytics", label: "View Analytics", group: "Analytics" },
    { key: "manage_settings", label: "System Settings", group: "Settings" },
];

export const MOCK_ORDERS: Order[] = [
    {
        id: "o1",
        wa_id: "254712001001",
        customer_name: "Amara Osei",
        items: [{ name: "Jollof Rice Combo", qty: 2, total: 800 }],
        subtotal: 800,
        status: "pending",
        payment: "mpesa",
        created_at: new Date(Date.now() - 18 * 60000).toISOString(),
    },
    {
        id: "o2",
        wa_id: "254712003003",
        customer_name: "Zara Diallo",
        items: [
            { name: "Egusi Soup", qty: 1, total: 450 },
            { name: "Puff Puff", qty: 3, total: 150 },
        ],
        subtotal: 600,
        status: "confirmed",
        payment: "cod",
        created_at: new Date(Date.now() - 35 * 60000).toISOString(),
    },
    {
        id: "o3",
        wa_id: "254712006006",
        customer_name: "Kweku Asante",
        items: [{ name: "Fufu Combo", qty: 2, total: 960 }],
        subtotal: 960,
        status: "delivered",
        payment: "mpesa",
        created_at: new Date(Date.now() - 3 * 3600000).toISOString(),
    },
    {
        id: "o4",
        wa_id: "254712007007",
        customer_name: "Akosua Frimpong",
        items: [{ name: "Waakye Special", qty: 1, total: 380 }],
        subtotal: 380,
        status: "confirmed",
        payment: "mpesa",
        created_at: new Date(Date.now() - 60 * 60000).toISOString(),
    },
];

export const MOCK_CATALOG: CatalogItem[] = [
    {
        id: "cat1",
        sku: "JRC-001",
        name: "Jollof Rice Combo",
        category: "Mains",
        price: 400,
        in_stock: true,
        description: "Smoky jollof rice with chicken and salad",
    },
    {
        id: "cat2",
        sku: "EGS-002",
        name: "Egusi Soup",
        category: "Mains",
        price: 450,
        in_stock: true,
        description: "Rich egusi soup with assorted fish",
    },
    {
        id: "cat3",
        sku: "FUF-003",
        name: "Fufu Combo",
        category: "Mains",
        price: 480,
        in_stock: true,
        description: "Cassava fufu with goat light soup",
    },
    {
        id: "cat4",
        sku: "WAK-004",
        name: "Waakye Special",
        category: "Mains",
        price: 380,
        in_stock: true,
        description: "Rice and beans with all toppings",
    },
    {
        id: "cat5",
        sku: "PLT-005",
        name: "Fried Plantain",
        category: "Sides",
        price: 150,
        in_stock: true,
        description: "Sweet golden fried plantain",
    },
    {
        id: "cat6",
        sku: "PUF-006",
        name: "Puff Puff",
        category: "Snacks",
        price: 50,
        in_stock: false,
        description: "Fluffy deep-fried dough balls",
    },
];

export const ACTIVITY_LOG: ActivityEntry[] = [
    {
        id: 1,
        user: "Sarah Kamau",
        action: "Intercepted conversation",
        target: "Amara Osei",
        at: new Date(Date.now() - 8 * 60000).toISOString(),
    },
    {
        id: 2,
        user: "Priya Sharma",
        action: "Added agent",
        target: "David Mwangi",
        at: new Date(Date.now() - 2 * 3600000).toISOString(),
    },
    {
        id: 3,
        user: "James Otieno",
        action: "Closed conversation",
        target: "Kweku Asante",
        at: new Date(Date.now() - 3 * 3600000).toISOString(),
    },
    {
        id: 4,
        user: "Sarah Kamau",
        action: "Updated order status",
        target: "#o2 → confirmed",
        at: new Date(Date.now() - 4 * 3600000).toISOString(),
    },
    {
        id: 5,
        user: "Priya Sharma",
        action: "Edited catalog item",
        target: "Puff Puff (out of stock)",
        at: new Date(Date.now() - 5 * 3600000).toISOString(),
    },
];
